/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javastdapp.admin;

import javastdapp.admin.businessLayer.Sportsmen;
import javastdapp.admin.FormForAddUsers;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javastdapp.admin.LoginForm;
import javastdapp.MyConnection;
import javastdapp.MyConnection;
import javastdapp.admin.MyFunction;
import javastdapp.admin.accessToInfo.AccessToInfoOfSportsmen;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Никита
 */
public class AddSportsmenForUsersForm extends javax.swing.JFrame {
    
    /**
     * Creates new form AddSportsmenForUsersForm
     */
    AccessToInfoOfSportsmen spt = new AccessToInfoOfSportsmen();
    Sportsmen sportsmen = new Sportsmen();
    
    public AddSportsmenForUsersForm() {
        initComponents();
        
        jComboBoxCountry.removeAllItems();
        jComboBoxSport.removeAllItems();
        spt.fillCountry(jComboBoxCountry);
        spt.fillSport(jComboBoxSport);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_FIO = new javax.swing.JTextField();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jTextField_Phone = new javax.swing.JTextField();
        jDateChooserBirthday = new com.toedter.calendar.JDateChooser();
        jButtonAddSportsmen = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField_Password = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxSport = new javax.swing.JComboBox<>();
        jComboBoxCountry = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel1.setText("Новый спортсмен");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Фамилия И.О.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("День рождения");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Телефон (логин)");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Пол");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Страна");

        jTextField_FIO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_FIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FIOActionPerformed(evt);
            }
        });

        jRadioButtonMale.setText("Муж");

        jRadioButtonFemale.setText("Жен");

        jTextField_Phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneActionPerformed(evt);
            }
        });
        jTextField_Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhoneKeyTyped(evt);
            }
        });

        jButtonAddSportsmen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddSportsmen.setText("Добавить");
        jButtonAddSportsmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSportsmenActionPerformed(evt);
            }
        });

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancel.setText("Отмена");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Пароль");

        jTextField_Password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PasswordActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Выбрать секцию");

        jComboBoxSport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Выбирите -" }));
        jComboBoxSport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBoxSportMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jComboBoxSportMouseReleased(evt);
            }
        });
        jComboBoxSport.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jComboBoxSportComponentResized(evt);
            }
        });
        jComboBoxSport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSportActionPerformed(evt);
            }
        });

        jComboBoxCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Выбирите -" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel12))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButtonAddSportsmen))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextField_Password, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField_FIO, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jDateChooserBirthday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jComboBoxSport, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jComboBoxCountry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jRadioButtonMale)
                                .addGap(34, 34, 34)
                                .addComponent(jRadioButtonFemale)))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2))
                    .addComponent(jTextField_FIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDateChooserBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jRadioButtonMale)
                    .addComponent(jRadioButtonFemale))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBoxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12)
                    .addComponent(jComboBoxSport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAddSportsmen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_FIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FIOActionPerformed

    private void jTextField_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneActionPerformed

    private void jTextField_PhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneKeyTyped

        if (!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_PhoneKeyTyped

    public boolean verifText(){
        
        if (jTextField_FIO.getText().equals("") || jTextField_Phone.getText().equals("") || jTextField_Password.getText().equals("")
                || jDateChooserBirthday.getDate() == null)
        {
            JOptionPane.showMessageDialog(null, "Одно или более полей пусты.");
            return false;
        }
        //choose a date higher then the current date
        else if (jDateChooserBirthday.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(null, "Невозможно добавить спортсмена из будущего.");
            return false;
        }
        else {
            return true;
        }
    }
    
    private void jButtonAddSportsmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSportsmenActionPerformed

        sportsmen.setFIO(jTextField_FIO.getText());
        sportsmen.setUserphone(jTextField_Phone.getText());
        sportsmen.setPassword(jTextField_Password.getText());
        sportsmen.setSex("М");
        String sport = (String)jComboBoxSport.getSelectedItem();
        
        if (jRadioButtonFemale.isSelected()){
            sportsmen.setSex("Ж");
        }
        
        if (verifText()){
            String country = (String)jComboBoxCountry.getSelectedItem();
            int 
                id_country = 0,
                id_sport = 0;
            
            Connection con = MyConnection.getConnection();
            Statement st;
            try {
                st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM COUNTRY");
                
                while (rs.next()){
                    if ( country.equals(rs.getString(2))){
                        sportsmen.setCountry(rs.getInt(1));
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(MyFunction.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM SPORT");
                
                while (rs.next()){
                    if ( sport.equals(rs.getString(2))){
                        sportsmen.setSport(rs.getInt(1));
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(MyFunction.class.getName()).log(Level.SEVERE, null, ex);
            }


            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            sportsmen.setBDate(dateFormat.format(jDateChooserBirthday.getDate()));
            
            spt.insertDeleteUpdate('i', 0, sportsmen);
            this.dispose();
            new LoginForm().setVisible(true);
            //MainForm.jLabel_SportsmenCount.setText("Всего в базе " + Integer.toString(MyFunction.countData("AccessToInfoOfSportsmen"))+ " спортсмена(ов)");

            //manageSportsmenForm.jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "Фамилия И.О.", "Телефон", "Дата рождения", "Пол", "Страна", "Спорт.секция"}));
            //spt.fillSportsmenJtable(manageSportsmenForm.jTable1, "");

        }

    }//GEN-LAST:event_jButtonAddSportsmenActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        //users.dispose(); //registr = new FormForAddUsers();
        this.dispose();
        //this.users = users;
        //FormForAddUsers users = new FormForAddUsers();
        FormForAddUsers registr = new FormForAddUsers();
            registr.setVisible(true);
            registr.setLocation(450, 50);
            registr.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        

    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextField_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PasswordActionPerformed

    private void jComboBoxSportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxSportMouseClicked
 
    }//GEN-LAST:event_jComboBoxSportMouseClicked

    private void jComboBoxSportMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBoxSportMouseReleased

    }//GEN-LAST:event_jComboBoxSportMouseReleased

    private void jComboBoxSportComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jComboBoxSportComponentResized

    }//GEN-LAST:event_jComboBoxSportComponentResized

    private void jComboBoxSportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSportActionPerformed

    }//GEN-LAST:event_jComboBoxSportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSportsmenForUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSportsmenForUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSportsmenForUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSportsmenForUsersForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSportsmenForUsersForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddSportsmen;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox<String> jComboBoxCountry;
    private javax.swing.JComboBox<String> jComboBoxSport;
    private com.toedter.calendar.JDateChooser jDateChooserBirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JTextField jTextField_FIO;
    private javax.swing.JTextField jTextField_Password;
    private javax.swing.JTextField jTextField_Phone;
    // End of variables declaration//GEN-END:variables
}
