/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javastdapp.admin;

import javastdapp.admin.businessLayer.Sportsmen;
import javastdapp.admin.accessToInfo.AccessToInfoOfSportsmen;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javastdapp.MyConnection;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Никита
 */
public class manageSportsmenForm extends javax.swing.JFrame {
    
    AccessToInfoOfSportsmen spt = new AccessToInfoOfSportsmen();
    Sportsmen sportsmen = new Sportsmen();
    DefaultTableModel model;
    
    public manageSportsmenForm() {
        initComponents();
        spt.fillSportsmenJtable(jTable1, "");
        ButtonGroup bg = new ButtonGroup();
        bg.add(jRadioButtonMale);
        bg.add(jRadioButtonFemale);
        spt.fillCountry(jComboBoxCountry);

        model = (DefaultTableModel)jTable1.getModel();
        jTable1.setRowHeight(35);
        jTable1.setShowGrid(true);
        jTable1.setGridColor(Color.lightGray);
        jTable1.setSelectionBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField_FIO = new javax.swing.JTextField();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jDateChooserBirthday = new com.toedter.calendar.JDateChooser();
        jButtonEditSportsmen = new javax.swing.JButton();
        jButtonRemoveSportsmen = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextField_SPT_ID = new javax.swing.JTextField();
        jButtonAddSportsmen1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField_Val_Find = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_Phone = new javax.swing.JTextField();
        jComboBoxCountry = new javax.swing.JComboBox<>();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("Информация о спортсменах");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Фамилия И.О.");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("День рождения");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Пол");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Страна");

        jTextField_FIO.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_FIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_FIOActionPerformed(evt);
            }
        });

        jRadioButtonMale.setText("Муж");

        jRadioButtonFemale.setText("Жен");

        jButtonEditSportsmen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonEditSportsmen.setText("Исправить");
        jButtonEditSportsmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditSportsmenActionPerformed(evt);
            }
        });

        jButtonRemoveSportsmen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonRemoveSportsmen.setText("Удалить");
        jButtonRemoveSportsmen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveSportsmenActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Id");

        jTextField_SPT_ID.setEditable(false);
        jTextField_SPT_ID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_SPT_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_SPT_IDActionPerformed(evt);
            }
        });

        jButtonAddSportsmen1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonAddSportsmen1.setText("Добавить");
        jButtonAddSportsmen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSportsmen1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Фамилия И.О.", "Телефон", "День рождения", "Пол", "Страна", "Спорт. секция"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(12);
        }

        jTextField_Val_Find.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Val_Find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField_Val_FindKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Ввидите для поиска");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Телефон");

        jTextField_Phone.setEditable(false);
        jTextField_Phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField_Phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_PhoneActionPerformed(evt);
            }
        });
        jTextField_Phone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PhoneKeyTyped(evt);
            }
        });

        jComboBoxCountry.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Выберите -" }));

        jButtonCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCancel.setText("Закрыть");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAddSportsmen1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonRemoveSportsmen, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonEditSportsmen))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(86, 86, 86)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(48, 48, 48)
                                    .addComponent(jRadioButtonMale)))
                            .addGap(29, 29, 29)
                            .addComponent(jRadioButtonFemale))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(jLabel11)
                                    .addGap(10, 10, 10)
                                    .addComponent(jTextField_SPT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(10, 10, 10)
                                    .addComponent(jTextField_FIO, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_Phone, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateChooserBirthday, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Val_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(202, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(331, 331, 331)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12)
                            .addComponent(jTextField_Val_Find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel11))
                            .addComponent(jTextField_SPT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2))
                            .addComponent(jTextField_FIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jDateChooserBirthday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonFemale)
                            .addComponent(jRadioButtonMale)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(128, 128, 128)
                        .addComponent(jButtonAddSportsmen1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEditSportsmen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRemoveSportsmen, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_FIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_FIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_FIOActionPerformed

    public boolean verifText(){
        
        String country = (String)jComboBoxCountry.getSelectedItem();
        if (jTextField_FIO.getText().equals("") || jDateChooserBirthday.getDate() == null)
        {
            JOptionPane.showMessageDialog(null, "Фамилия И.О не заполнены.");
            return false;
        }
        else if (jTextField_Phone.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Телефон не заполнен.");
            return false;
        }
        else if ("- Выбирите -".equals(country)) {
            JOptionPane.showMessageDialog(null, "Страна не выбрана.");
            return false;
        }
        //choose a date higher then the current date
        else if (jDateChooserBirthday.getDate().compareTo(new Date()) > 0) {
            JOptionPane.showMessageDialog(null, "Невозможно добавить спортсмена из будущего.");
            return false;
        }
        else {
            return true;
        }
    }
    
    private void jButtonEditSportsmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditSportsmenActionPerformed

        sportsmen.setFIO(jTextField_FIO.getText());
        sportsmen.setUserphone(jTextField_Phone.getText());
        
        int id_s = Integer.valueOf(jTextField_SPT_ID.getText());
        sportsmen.setSex("М");
        if (jRadioButtonFemale.isSelected()){
            sportsmen.setSex("Ж");
        }
        
        if (verifText()){
            String country = (String)jComboBoxCountry.getSelectedItem();
            int
            id_country = 0;

            Connection con = MyConnection.getConnection();
            Statement st;
            try {
                st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM COUNTRY");

                while (rs.next()){
                    if ( country.equals(rs.getString(2))){
                        sportsmen.setCountry(rs.getInt(1));
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(MyFunction.class.getName()).log(Level.SEVERE, null, ex);
            }


            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            sportsmen.setBDate(dateFormat.format(jDateChooserBirthday.getDate()));
            sportsmen.setPassword(null);
            sportsmen.setSport(0);

            spt.insertDeleteUpdate('u', id_s, sportsmen);
            spt.fillSportsmenJtable(jTable1, "");
            jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "Фамилия И.О.", "Телефон", "Дата рождения", "Пол", "Страна", "Спорт.секция"}));
            spt.fillSportsmenJtable(jTable1, jTextField_Val_Find.getText());
            //MainForm.jLabel_SportsmenCount.setText("Всего в базе " + Integer.toString(MyFunction.countData("AccessToInfoOfSportsmen"))+ " спортсмена(ов)");
        
        }

    }//GEN-LAST:event_jButtonEditSportsmenActionPerformed

    private void jButtonRemoveSportsmenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveSportsmenActionPerformed
        
        if(jTextField_SPT_ID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Сортсмен не выбран.");
        }else {
                
        int id_s = Integer.valueOf(jTextField_SPT_ID.getText());
        Sportsmen sm = new Sportsmen(null, null, null, null, null, 0, 0);
        
        spt.insertDeleteUpdate('d', id_s, sm);
            
        spt.fillSportsmenJtable(jTable1, "");
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "Фамилия И.О.", "Телефон", "Дата рождения", "Пол", "Страна", "Спорт.секция"}));
        spt.fillSportsmenJtable(jTable1, jTextField_Val_Find.getText());
        MainForm.jLabel_SportsmenCount.setText("Всего в базе " + Integer.toString(MyFunction.countData("Sportsmen"))+ " спортсмена(ов)");
        
        jTextField_SPT_ID.setText("");
        jTextField_FIO.setText("");
        jTextField_Phone.setText("");
        spt.fillSport(jComboBoxCountry);
        jRadioButtonFemale.setSelected(false);
        jRadioButtonMale.setSelected(false);
        jDateChooserBirthday.setDate(null);
        
        }            
    }//GEN-LAST:event_jButtonRemoveSportsmenActionPerformed

    private void jTextField_SPT_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_SPT_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_SPT_IDActionPerformed

    private void jButtonAddSportsmen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSportsmen1ActionPerformed
        
        AddSportsmenForm AddSf = new AddSportsmenForm();
        AddSf.setVisible(true);
        AddSf.pack();
        AddSf.setLocationRelativeTo(null);
        AddSf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jButtonAddSportsmen1ActionPerformed

    int rowIndex;
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        
        rowIndex = jTable1.getSelectedRow();
        model = (DefaultTableModel)jTable1.getModel();
        
        if(model.getValueAt(rowIndex, 4).toString().equals("М")){
            jRadioButtonMale.setSelected(true);
            jRadioButtonFemale.setSelected(false);
        }
        else {
            jRadioButtonFemale.setSelected(true);
            jRadioButtonMale.setSelected(false);
        }
        
        jTextField_SPT_ID.setText(model.getValueAt(rowIndex, 0).toString());
        jTextField_FIO.setText(model.getValueAt(rowIndex, 1).toString());
        jTextField_Phone.setText(model.getValueAt(rowIndex, 2).toString());
        jComboBoxCountry.setSelectedItem(model.getValueAt(rowIndex, 5));
        
        
        Date bdate;
        try {
            bdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 3).toString());
            jDateChooserBirthday.setDate(bdate);
        } catch (ParseException ex) {
            Logger.getLogger(manageSportsmenForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        /*String country = "";
        int index = (int) model.getValueAt(rowIndex, 4);
        
        Connection con = MyConnection.getConnection();
        Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT * FROM COUNTRY");
                
            while (rs.next()){
                if ( index == rs.getInt(1)){
                    country = rs.getString(2);
                }
            }
            jTextField_Country.setText(country);
        } catch (SQLException ex) {
            Logger.getLogger(MyFunction.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }//GEN-LAST:event_jTable1MouseClicked

    private void jTextField_Val_FindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Val_FindKeyReleased
              
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"ID", "Фамилия И.О.", "Телефон", "Дата рождения", "Пол", "Страна"}));
        spt.fillSportsmenJtable(jTable1, jTextField_Val_Find.getText());
    }//GEN-LAST:event_jTextField_Val_FindKeyReleased

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        
        if(evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_DOWN)
        {
            rowIndex = jTable1.getSelectedRow();
       
        
            if(model.getValueAt(rowIndex, 3).toString().equals("М")){
                jRadioButtonMale.setSelected(true);
                jRadioButtonFemale.setSelected(false);
            }
            else {
                jRadioButtonFemale.setSelected(true);
                jRadioButtonMale.setSelected(false);
            }

            jTextField_SPT_ID.setText(model.getValueAt(rowIndex, 0).toString());
            jTextField_FIO.setText(model.getValueAt(rowIndex, 1).toString());
            jComboBoxCountry.setSelectedItem(model.getValueAt(rowIndex, 5));

            Date bdate;
            try {
                bdate = new SimpleDateFormat("yyyy-MM-dd").parse(model.getValueAt(rowIndex, 2).toString());
                jDateChooserBirthday.setDate(bdate);
            } catch (ParseException ex) {
                Logger.getLogger(manageSportsmenForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
            /*String country = "";
            int index = (int) model.getValueAt(rowIndex, 4);

            Connection con = MyConnection.getConnection();
            Statement st;
            try {
                st = con.createStatement();
                ResultSet rs = st.executeQuery("SELECT * FROM COUNTRY");

                while (rs.next()){
                    if ( index == rs.getInt(1)){
                        country = rs.getString(2);
                    }
                }
                jTextField_Country.setText(country);
            } catch (SQLException ex) {
                Logger.getLogger(MyFunction.class.getName()).log(Level.SEVERE, null, ex);
            }*/
        }
        
    }//GEN-LAST:event_jTable1KeyReleased

    private void jTextField_PhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_PhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_PhoneActionPerformed

    private void jTextField_PhoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PhoneKeyTyped

        if (!Character.isDigit(evt.getKeyChar())){
            //evt.consume();
            jTextField_Phone.setEditable(false);
        }
    }//GEN-LAST:event_jTextField_PhoneKeyTyped

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        this.dispose();
        MainForm mf = new MainForm();
        mf.setVisible(true);
        mf.pack();
        mf.setLocationRelativeTo(null);
        mf.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        MainForm.jLabel_SportsmenCount.setText("Всего в базе спортсменов: " + Integer.toString(MyFunction.countData("Sportsmen"))+ " ");
        MainForm.jLabel_TrainerCount.setText("Всего в базе тренеров: " + Integer.toString(MyFunction.countData("Trainer"))+ " ");
        MainForm.jLabel_CompetitionCount.setText("Всего в базе соревнований: " + Integer.toString(MyFunction.countData("Competition"))+ " ");

    }//GEN-LAST:event_jButtonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageSportsmenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageSportsmenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageSportsmenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageSportsmenForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageSportsmenForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddSportsmen1;
    private javax.swing.JButton jButtonCancel;
    public static javax.swing.JButton jButtonEditSportsmen;
    private javax.swing.JButton jButtonRemoveSportsmen;
    private javax.swing.JComboBox<String> jComboBoxCountry;
    private com.toedter.calendar.JDateChooser jDateChooserBirthday;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField_FIO;
    private javax.swing.JTextField jTextField_Phone;
    private javax.swing.JTextField jTextField_SPT_ID;
    private javax.swing.JTextField jTextField_Val_Find;
    // End of variables declaration//GEN-END:variables
}
